FROM almalinux:9
ENV course="Devops with AWS" \
    trainer="Anil" \
    Duration="120HRS"
#username is KEY and some_user is default value  
ARG USERNAME=Anil
RUN echo "Hello user: ${USERNAME}" > /tmp/devops.txt
CMD ["sleep" ,"100"]